### ISSUE TITLE
Hawaii nodes

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#10]
1. Need access and install latest version of code

**Comment by xi-yang** [comment]
Added to sense-o.es.net. 

The model looks good but all the Python processes have crashed on the FE pod. So the model must be an old one.

@juztas I left the FE pod as is so you can investigate the crashed processes. 

I also see all FE Python processes crashed on the MAX site. This has been a constant and widespread stability issue across all sites. Can we fix this and create a stable release, and then have a procedure in place for future stable releases?

**Comment by juztas** [comment]
There are no logs :D Kubernetes does not keep all log we need for longer time. It failed to get config from git - so process is kept down (in 99% times it shows node issue not able to communicate with outside)

**Comment by juztas** [comment]
Same UMD - no logs - so seems it keeps only last x hours. They still run old release, and not the new one. New one to be released soon - once we have L3 ruled out.

**Comment by xi-yang** [comment]
So the issue with both hawii and max FE was not being able to get config from git. Couple of questions:
- Why did that happen to these two sites? 
- How should we get around this with the current code?
- What are we going to do to avoid this in the new code?

**Comment by juztas** [comment]
Lets discuss it on issue (most times it fails on Kubernetes, so why it looses network connection to outside - good question).
https://github.com/sdn-sense/siterm/issues/17
We can do try/except/sleep and wait for it to be back - but this does not sound right and just hiding the real issue  "under the carpet".

I will add Hawaii node to prometheus, so it alarms me when it crashes.

**Comment by xi-yang** [comment]
So it was a K8s issue. Let's take notes for all these failure scenarios and try coming up with a plan to properly work around or report errors for all. 

Going forward, we should more rely on k8s for deployment automation and health check. Our admin tools should focus on this environment. I think most of the community will take this recommendation. 

We will also support straight Docker deployments but with limited support for admin tools. This will cover other cases with reduced support.

**Comment by juztas** [comment]
From code side - we will have this wrapped around and notified. And moving forward - all Site-RM FE/Agent deployment is preferably done by Site Representatives and we from SENSE team only cover a few handful sites which we use for operations, development. And here is notification ticket: https://github.com/sdn-sense/siterm/issues/66 - with which we instruct Orchestrator, Influx, and Site about the failure in service.

**Comment by xi-yang** [comment]
Notifying the site admin will sometimes be a long roundtrip, even for a simple restart. 

Firstly we do need to keep the site admin in the loop.

In addition, we should make the code more robust so it can run for weeks without crash. (currently days on average). When a process crashed, we should have policy in K8s (or some other tool for straight docker) to auto restart the container. The implication is that the operation states should be reboot resistant, at least for a graceful restart. For example, when a delta is in processing, a restart will disrupt it and fail the operation. But after the restart, a retry of delta should work without experiencing any state corruption.

These may take some iterations to achieve but I think we should aim towards that direction.

**Comment by juztas** [comment]
Lets followup on this in https://github.com/sdn-sense/siterm/issues/99

I am closing this ticket, Hawaii node installed.
