### ISSUE TITLE
Max nodes

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#12]
@xi-yang I do not have access to DTN itself (132), but I can access all via Kubernetes. 

Just give me green light if it is good to reinstall.

**Comment by xi-yang** [comment]
yes, you can reinstall on 131, 132 and 134.

To access on 132 and 134. Login to 131 with `jbacas`. Then just ssh to the others with root login.

**Comment by xi-yang** [comment]
Note that these hosts may be gone in weeks. MAX will get rid of them in a hardware migration. We will need to redeploy on new hardware.

**Comment by juztas** [comment]
Ok, Thanks! I will use those as testing now to automate deployment on Kubernetes. Once there are new ones, we will be able to migrate easily.

**Comment by juztas** [comment]
UMD Upgrade. @xi-yang please give a try to test it and let me know

**Comment by juztas** [comment]
Whole Kubernetes was reinstalled and was used for Kubernetes automation. From the deployment side - it is all good.
