### ISSUE TITLE
Amlight/RNP Node access and upgrade

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#13]
I need to get access to those DTNs and get software updated, latest.
ox.amlight.net
200.159.252.130

@xi-yang

**Comment by xi-yang** [comment]
Check with Marcos. Just send him an email. 

BTW, we do not have root access on this host. All configs and operations have to be done by Marcos.

**Comment by juztas** [comment]
Email sent twice. No reply. Also as we do not have access to this - I moved it to preprod state (which is not maintained by us).
We will need a mailing list or such - to inform sites get the latest release and deploy it.

Closing
