### ISSUE TITLE
Geant nodes

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#16]
Any Geant DTNs? If so - need access to those and will need more details, like isAlias, ips, vlans. And or if we want to have network control.

@tomlehman

**Comment by xi-yang** [comment]
Only CERN DTN if that counts. 

There is a KIT DTN (Bruno's) that is no longer active but they may ask to reactivate before SC22.

**Comment by juztas** [comment]
KIT has a separate issue, Cern is in place (and working ppc64le container). Tom's diagram had GEANT as Site - so if this is CERN - nothing to do. Closing ticket, reopen if needed.
