### ISSUE TITLE
Starlight RM stuck in committing status

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/ops#21]
Possibly the agent on dtn110 (k8s node) is having problem. 

Try `Starlight-dtn110-debug` on sense-o. 

Note that we can upgrade the site with the latest stable code and then try again. @juztas

**Comment by juztas** [comment]
Starlight was not yet updated. (will update today)

**Comment by juztas** [comment]
Starlight redeployed. I think it conflicts with Kubernetes/docker iptables. Informed owners of DTN to look at port opening
