### ISSUE TITLE
Upgrade Hawaii site and retest the three DTNs

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/ops#22]
The site has three DTN servers
```
urn:ogf:network:hawaii.edu:2022:fiona.its.hawaii.edu
urn:ogf:network:hawaii.edu:2022:k8s-dtn-01.uog.edu
urn:ogf:network:hawaii.edu:2022:prp01.ifa.hawaii.edu
```

`prp01.ifa.hawaii.edu` had never worked correctly. The other two worked but had recently stopped working correctly.

**Comment by juztas** [comment]
Which issues you are facing? I found one issue: https://github.com/sdn-sense/siterm/pull/139 but that should still allow to get deltas in, only QoS would fail.

**Comment by xi-yang** [comment]
prp01 had never worked. 

The other two failed to propagate or commit in my tests two weeks ago.

**Comment by juztas** [comment]
Done. All Hawaii nodes are up to date.
