### ISSUE TITLE
UCSD Site-RM propagate error.

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/ops#24]
RM Internal Error - {"error_description": "{\"ID\": \"0d73e423-cfbc-4836-ad08-cc426a5764ac\", \"InsertTime\": 1664815216, \"UpdateTime\": 1664815216, \"Content\": {\"modelId\": \"8dede315-4338-11ed-8e71-000000010320\", \"id\": \"0d73e423-cfbc-4836-ad08-cc426a5764ac\", \"lastModified\": \"2022-10-03T16:40:16.306+0000\", \"reduction\": \"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\\n@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\n@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\\n\\nowl:FunctionalProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:InverseFunctionalProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:OntologyProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nrdfs:ContainerMembershipProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nrdf:List  a                  owl:Class ;\\n        rdfs:subClassOf      rdf:List ;\\n        owl:equivalentClass  rdf:List .\\n\\nowl:TransitiveProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:ObjectProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nowl:DatatypeProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nowl:Ontology  a              owl:Class ;\\n        rdfs:subClassOf      owl:Ontology ;\\n        owl:equivalentClass  owl:Ontology .\\n\\nowl:SymmetricProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nrdf:Statement  a             owl:Class ;\\n        rdfs:subClassOf      rdf:Statement ;\\n        owl:equivalentClass  rdf:Statement .\\n\\nowl:Property  a              owl:Class ;\\n        rdfs:subClassOf      owl:Property ;\\n        owl:equivalentClass  owl:Property .\\n\\nrdfs:Literal  a              owl:Class ;\\n        rdfs:subClassOf      rdfs:Literal ;\\n        owl:equivalentClass  rdfs:Literal .\\n\", \"addition\": \"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\\n@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\n@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988:label+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3988\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw>\\n        <http://schemas.ogf.org/mrs/2013/12/topology#providesSubnet>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw:conn+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy-Connection_1:vlan+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988:label+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3988\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw:conn+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy-Connection_1:vlan+3988>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#encoding>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988> , <urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labelSwapping>\\n                \\\"false\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw:conn+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy-Connection_1:vlan+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988:label+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988:service+bw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#isAlias>\\n                <urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:label+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3988\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:service+vsw:conn+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy-Connection_1:vlan+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988:label+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988:service+bw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#isAlias>\\n                <urn:ogf:network:calit2.optiputer.net:2020:prism-core:k8s-igrok-01:vlanport+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:ipv4-address+172.31.10.5>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#NetworkAddress> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+ip-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"unverifiable\\\" , \\\"ipv4-address\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#value>\\n                \\\"172.31.10.5/24\\\" .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_2>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#hasNetworkAddress>\\n                <urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:ipv4-address+172.31.10.5> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+d2316708-5b6a-4e07-8434-5f1addff4a58:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:label+3988> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:nrp-nautilus.io:2020:k8s-igrok-01.calit2.optiputer.net:enp33s0f1:vlanport+3988:service+bw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#isAlias>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_2:vlanport+3988> .\\n\\n<urn:ogf:network:nrp-nautilus.io:2020:s0:1_1>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:nrp-nautilus.io:2020:s0:1_1:vlanport+3988> .\\n\"}, \"State\": \"failed\", \"modelId\": \"8dede315-4338-11ed-8e71-000000010320\", \"Type\": \"submission\", \"modadd\": \"idle\", \"Error\": {\"errType\": \"<class 'DTNRMLibs.CustomExceptions.OverlapException'>\", \"errNo\": \"-7\", \"errMsg\": \"Vlan {'interface': '1_1', 'vlan': 3988} not available for switch s0 in configuration.                                        Either used or not configured.\"}}", "exitCode": 500}

**Comment by xi-yang** [comment]
Similar error occurred to UMD RM:

RM Internal Error - {"error_description": "{\"ID\": \"dab3f5b4-c692-452e-b81c-d8c000a8aa7a\", \"InsertTime\": 1664815662, \"UpdateTime\": 1664815662, \"Content\": {\"modelId\": \"3538ceb8-4335-11ed-81eb-0000000043a9\", \"id\": \"dab3f5b4-c692-452e-b81c-d8c000a8aa7a\", \"lastModified\": \"2022-10-03T16:47:42.547+0000\", \"reduction\": \"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\\n@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\n@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\\n\\nowl:FunctionalProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:InverseFunctionalProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:OntologyProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nrdfs:ContainerMembershipProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nrdf:List  a                  owl:Class ;\\n        rdfs:subClassOf      rdf:List ;\\n        owl:equivalentClass  rdf:List .\\n\\nowl:TransitiveProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nowl:ObjectProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nowl:DatatypeProperty  rdfs:subClassOf  rdfs:Resource .\\n\\nowl:Ontology  a              owl:Class ;\\n        rdfs:subClassOf      owl:Ontology ;\\n        owl:equivalentClass  owl:Ontology .\\n\\nowl:SymmetricProperty\\n        rdfs:subClassOf  rdfs:Resource .\\n\\nrdf:Statement  a             owl:Class ;\\n        rdfs:subClassOf      rdf:Statement ;\\n        owl:equivalentClass  rdf:Statement .\\n\\nowl:Property  a              owl:Class ;\\n        rdfs:subClassOf      owl:Property ;\\n        owl:equivalentClass  owl:Property .\\n\\nrdfs:Literal  a              owl:Class ;\\n        rdfs:subClassOf      rdfs:Literal ;\\n        owl:equivalentClass  rdfs:Literal .\\n\", \"addition\": \"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\\n@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\n@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\\n\\n<http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet>\\n        a                    owl:Class , rdfs:Class , rdfs:Resource ;\\n        rdfs:subClassOf      <http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet> , rdfs:Resource ;\\n        owl:equivalentClass  <http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:ipv4-address+172.31.7.47>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#NetworkAddress> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+ip-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"unverifiable\\\" , \\\"ipv4-address\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#value>\\n                \\\"172.31.7.47/24\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605:service+bw>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#BandwidthService> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#availableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#granularity>\\n                \\\"1000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#maximumCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#priority>\\n                \\\"0\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#reservableCapacity>\\n                \\\"1000000000\\\"^^xsd:long ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#type>\\n                \\\"guaranteedCapped\\\" ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#unit>\\n                \\\"bps\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#hasNetworkAddress>\\n                <urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:ipv4-address+172.31.7.47> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:label+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:service+bw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#isAlias>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605:label+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3605\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:service+vsw:conn+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy-Connection_1:vlan+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605:label+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605:service+bw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#isAlias>\\n                <urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605:label+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3605\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:service+vsw:conn+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy-Connection_1:vlan+3605>\\n        a       <http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:service+vsw> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#encoding>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605> , <urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labelSwapping>\\n                \\\"false\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_2>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlanport+3605> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3605> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#BidirectionalPort> ;\\n        <http://schemas.ogf.org/mrs/2013/12/topology#tag>\\n                \\\"urn:ogf:network:service+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy::Connection_1\\\" ;\\n        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:service+vsw:conn+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy-Connection_1:vlan+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasLabel>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605:label+3605> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#hasService>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605:service+bw> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605:label+3605>\\n        a       <http://schemas.ogf.org/nml/2013/03/base#Label> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#labeltype>\\n                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;\\n        <http://schemas.ogf.org/nml/2013/03/base#value>\\n                \\\"3605\\\" .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:1_1>\\n        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlanport+3605> .\\n\\n<urn:ogf:network:maxgigapop.net:2013:s0:service+vsw>\\n        <http://schemas.ogf.org/mrs/2013/12/topology#providesSubnet>\\n                <urn:ogf:network:maxgigapop.net:2013:s0:service+vsw:conn+495363fd-bdf8-4082-aa33-b4c535bedafa:vt+l2-policy-Connection_1:vlan+3605> .\\n\\n<http://schemas.ogf.org/nml/2013/03/base#Label>\\n        a       rdfs:Resource , rdfs:Class .\\n\"}, \"State\": \"failed\", \"modelId\": \"3538ceb8-4335-11ed-81eb-0000000043a9\", \"Type\": \"submission\", \"modadd\": \"idle\", \"Error\": {\"errType\": \"<class 'DTNRMLibs.CustomExceptions.OverlapException'>\", \"errNo\": \"-7\", \"errMsg\": \"Vlan {'interface': '1_1', 'vlan': 3605} not available for switch s0 in configuration.                                        Either used or not configured.\"}}", "exitCode": 500}

**Comment by juztas** [comment]
Defined vlan_range globally at virtual switch level: https://github.com/sdn-sense/rm-configs/commit/5a7cab47b6a8d87cb0a2ea45d50e715a138345ef
Issue created: https://github.com/sdn-sense/siterm/issues/213

I will restart all FEs. Config changes do not restart httpd service - so needs to be done manually (restart)

**Comment by juztas** [comment]
@xi-yang UMD and UCSD containers restarted - try and let me know. If all good - will restart all remaining ones

**Comment by xi-yang** [comment]
Both works now. I just created a connection UCSD -- UMD and was able to ping.
