### ISSUE TITLE
T3_US_Starlight deployment

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#4]
T3_US_Starlight have 2 dtns defined. 
1st: 165.124.33.142 and fe running in VM here: sense-rm.northwestern.edu - this should be OK. It uses the following config files: https://github.com/sdn-sense/rm-configs/tree/master/T3_US_Starlight
2nd - (165.124.33.233) - seems to need an update. What is correct isAlias? If same as 1st - then it can be joined as a second DTN without 2 separate frontends. 

@xi-yang let me know what are the issues with those and what needs to be done.

**Comment by xi-yang** [comment]
The 2nd used to connect through ESnet-Testbed. We decommissioned the ESnet Testbed RM. So that isAlias is no longer relevant. Let's check with Starlight to see if they want to keep this DTN in SENSE.

**Comment by xi-yang** [comment]
isAlias is `urn:ogf:network:icair.org:2013:mren8700:r740xd4`. We will put this as a second node in the Starlight site. @juztas

**Comment by juztas** [comment]
@xi-yang I see there are 2 Starlight nodes, one is under Kubernetes (urn:ogf:network:icair.org:2013:mren8700:dtn110) and another under docker (urn:ogf:network:icair.org:2013:mren8700:r740xd4)

We should reinstall both and make it in sync (only docker or only Kubernetes)? Also depends if we want to connect both DTNs to a same FE (simplify deployment)

**Comment by xi-yang** [comment]
We still have access dtn110. I am not sure the status of the other. Maybe we should leave that out. 

For dtn110, the agent is on the k8s with pod on that host. The FE is on `sense-rm.northwestern.edu`.

**Comment by juztas** [comment]
@xi-yang who manages Starlight? We should ask what is the status/plan (Could you drop an email to admin of Starlight nodes?)

**Comment by juztas** [comment]
Starlight redeployed. I think it conflicts with Kubernetes/docker iptables. Informed owners of DTN to look at port opening

**Comment by juztas** [comment]
Second DTN no DNS Entries:
```
-bash-4.2$ nslookup 165.124.33.233
** server can't find 233.33.124.165.in-addr.arpa.: NXDOMAIN
```

**Comment by juztas** [comment]
As mentioned on Slack:
```
[@Xi Yang (ESnet)](https://nren.slack.com/team/U01CUQV8X0W)
 could test (I do not have access to sense-o/dev). 
[@Xi Yang (ESnet)](https://nren.slack.com/team/U01CUQV8X0W)
 endpoint is: https://dtn110.sl.startap.net:8443/T3_US_Starlight/sitefe/v1
```
For no DNS - Starlight will add entry

**Comment by juztas** [comment]
@xi-yang starlight both dtns deployed. Ednpoint is: https://dtn110.sl.startap.net:8443/T3_US_Starlight/sitefe/v1 Let me know if something is off.
