### ISSUE TITLE
cixp-surfnet-dtn.cern - update to latest code release

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#5]
@xi-yang I do not have access to this and also there are no configs.

I will need to know isAlias and which ports can be used for SENSE. If not needed anymore, go ahead and close the ticket.

**Comment by xi-yang** [comment]
Config is here: https://github.com/sdn-sense/rm-configs/tree/master/T2_CH_CERN

It is powerPC box. The DTN-RM there has been incredibly stable in the past. But we do need to review and update it to the latest code.

**Comment by xi-yang** [comment]
ssh dtn@192.91.245.27

**Comment by juztas** [comment]
Upgraded, please use fqdn: https://cixp-surfnet-dtn.cern.ch:8443

**Comment by juztas** [comment]
Reinstalled, comfired by Xi as being good. Closing
