### ISSUE TITLE
urn:ogf:network:kreonet.net:2013 - no access

### ISSUE THREAD

**Issue by juztas** [sdn-sense/ops#7]
@xi-yang

**Comment by xi-yang** [comment]
I have no access either. Kreonet did their own install. I am not sure what is the plan there. @tomlehman can follow up on this.

**Comment by juztas** [comment]
@tomlehman any follow up on this?

To better support - access would be preferred.

**Comment by juztas** [comment]
No access, they deploy themselves. Closing, reopen if needed.
